apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hotel-ing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /hotels  #Temporaly redirects application root to /hotels
spec:
  rules:
  - host: app.hotel.com
    http:
      paths:
      - backend:
          serviceName: golang-app
          servicePort: {{ .Values.service.port }} 
        path: /

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hotel-ing-canary
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "30" #Serve 30% traffic to java application
    nginx.ingress.kubernetes.io/app-root: /hotels #Temporaly redirects application root to /hotels
spec:
  rules:
  - host: app.hotel.com
    http:
      paths:
      - backend:
          serviceName: java-app
          servicePort: {{ .Values.service.port }} 
        path: /