name: Add issue to project
on:
  issues:
    types:
      - opened
      - reopened
      - transferred

  
jobs:
  track_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
          PROJECT_NUMBER: 1
          ACCOUNT: daddychukz
        run: |
          gh api graphql --header 'GraphQL-Features: projects_next_graphql' -f query='
            query($account: String!, $number: Int!) {
              user(login: $account){
                projectNext(number: $number) {
                  id
                  
                }
              }
            }' -f account=$ACCOUNT -F number=$PROJECT_NUMBER 

          
