name: Add issue to project
on:
  issues:
    types:
      - opened
      - reopened
      - transferred
      - closed

env:
  GITHUB_TOKEN: ${{ secrets.MY_PAT }}
  PROJECT_NUMBER: 1
  USER: daddychukz
  
jobs:
  track_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        run: |
          gh api graphql --header 'GraphQL-Features: projects_next_graphql' -f query='
            query($user: String!, $number: Int!) {
              user(login: $user){
                projectNext(number: $number) {
                  id
                  fields(first:20) {
                    nodes {
                      id
                      name
                      settings
                    }
                  }
                }
              }
            }' -f user=$USER -F number=$PROJECT_NUMBER > data.json
            
          cat data.json

          
